-- AlterTable
ALTER TABLE "InspeccionDetalle" ALTER COLUMN "foto1Url" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "foto2Url" SET DATA TYPE VARCHAR(255),
ALTER COLUMN "foto3Url" SET DATA TYPE VARCHAR(255);
